---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: false
  tasks:
    - name: Install Erlang Repository Package
      ansible.builtin.apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
      tags:
        - package

    - name: Add an Erlang Solution public Key
      ansible.builtin.apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      tags:
        - package

    - name: Install Erlang
      ansible.builtin.apt:
        name: erlang
        update_cache: yes
        cache_valid_time: 86400
        state: present
      tags:
        - package

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present
      tags:
        - package

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
        state: present
      tags:
        - package

    - name: Install Rabbit MQ
      ansible.builtin.apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
      tags:
        - package

    - name: Start & Enable RMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Config setup
      ansible.builtin.copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf

    - name: Add user to server
      community.rabbitmq.rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf

    - name: Enables the rabbitmq_management plugin
      community.rabbitmq.rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted