---
- name: Setup Nginx svc
  hosts: websrvgrp
  gather_facts: false
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package

    - name: Start & ENable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - svc

    - name: Disable Nginx default website
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - conf

    - name: Deploy web config file
      ansible.builtin.template:
        src: templates/nginxvpro.j2
        dest: /etc/nginx/sites-available/vproapp
      tags:
        - conf

    - name: Enable vproapp website
      ansible.builtin.file:
        src: /etc/nginx/sites-available/vproapp
        dest: /etc/nginx/sites-enabled/vproapp
        state: link
      notify:
        - Restart Nginx
      tags:
        - conf

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted